### PR TITLE
CimCmdlet 폴더 추가 및, Export-BinaryMiLog.md 번역

### PR DESCRIPTION
**Pull request by tlqaksqhr**
CimCmdlet 폴더 추가 및, Export-BinaryMiLog.md 번역

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs.ko-kr/2)

### CODE REVIEW

**Comment by tlqaksqhr** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs.ko-kr/2)*

**Comment by tlqaksqhr** [comment]
review completed?

---







*Comments from [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs.ko-kr/2#-:-LFqIsIb-HzCECaTYRIx:b-42vo09)*

**Comment by v-radelg** [comment]
Hello @tlqaksqhr  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @tlqaksqhr 

Thank you so much for your valuable contribution. Due to some changes currently being made to the file formats, we cannot localize this file at the moment. We do value your feedback and please rest assured that we are not discarding your translation and we will take it into consideration as we will start localizing the content in the near future.

Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

cc @sara-nicolini @sunnydeng

**Comment by v-radelg** [comment]
Hi @tlqaksqhr

Thank you so much for your valuable contribution. Due to some changes currently being made to the file formats, we cannot localize this file at the moment. We do value your feedback and please rest assured that we are not discarding your translation and we will take it into consideration as we will start localizing the content in the near future.

Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

cc @sara-nicolini @ishasahni1 

 #please-translate

**Comment by v-radelg** [comment]
안녕하세요 @tlqaksqhr님
귀하의 귀중한 공헌에 매우 감사드립니다. 파일 포맷에 일부 변경이 진행 중인 관계로 현재 본 파일을 현지화할 수 없습니다. 귀하의 의견은 저희에게 매우 소중하며, 귀하의 번역을 폐기하지 않고 조만간 컨텐츠 현지화를 시작하면서 참고할 것이니 안심하셔도 좋습니다. 
귀중한 시간을 내주셔서 감사합니다.

관심을 가져 주셔서 감사합니다.
Microsoft C&E 로컬라이제이션 팀

**Comment by tlqaksqhr** [comment]
Thanks :D

**Pull request closed without merging**
