### PR TITLE
Correct to natural Korean

### PR DESCRIPTION
**Pull request by ryoma328**
Correct to natural Korean

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs.ko-kr/3)

### CODE REVIEW

**Comment by v-tisip** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by v-elcou** [comment]
Hello, @ryoma328, 
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by LisandroSu** [comment]
Hello, @ryoma328 

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The file was deleted from the repo so the PR will be closed instead of merged.
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request closed without merging**
